### PR TITLE
3 database

### PR DESCRIPTION
**Pull request by Leshens**
- [x] BD w kontenerze(zobacz mój stary projekt)
- [x] MySql
- [x] randomowe dnane
- [x] testy manualne
- [x] Table:

  id
  userId
  restaurantName
  tables[]
  location
 - [x] CRUDE

### CODE REVIEW

**Comment by Leshens** [comment]
@sugarvalley proszę o PR rewiew

**Comment by Leshens** [comment]
> # Obey the Standard Model, or obey the laws of death. ~Fabricator-General Sin Cosinius

**Review by sugarvalley — APPROVED** [review]
bardzo profesjonalnie zrobione

**Comment by sugarvalley** [comment]
fail check dockera

**Pull request merged**
